# Generated by Django 4.1.5 on 2023-01-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
