# Generated by Django 4.0.1 on 2023-01-17 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0002_register_password_register_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default=True, max_length=1000)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polling.register')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op1', models.CharField(default=True, max_length=1000)),
                ('like', models.CharField(default=True, max_length=100)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polling.register')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polling.questions')),
            ],
        ),
    ]
