# Generated by Django 4.1.5 on 2023-01-18 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0003_alter_register_phone_questions_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(default=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polling.register')),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='op1',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='questions',
            name='op2',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='questions',
            name='op3',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='questions',
            name='op4',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.DeleteModel(
            name='Options',
        ),
        migrations.AddField(
            model_name='poll',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polling.questions'),
        ),
    ]
