# Generated by Django 4.1.5 on 2023-01-18 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0005_remove_poll_like_remove_questions_op2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='name',
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polling.questions'),
        ),
    ]
