# Generated by Django 4.1.5 on 2023-01-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0006_remove_poll_name_alter_poll_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='like',
            new_name='Vote',
        ),
    ]
