# Generated by Django 4.1.5 on 2023-01-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0007_rename_like_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='op1',
        ),
    ]
