# Generated by Django 4.1.5 on 2023-01-19 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0008_remove_questions_op1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='op1',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='vote',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polling.questions'),
        ),
        migrations.DeleteModel(
            name='poll',
        ),
    ]
