# Generated by Django 4.1.5 on 2023-01-19 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0009_alter_vote_op1_alter_vote_question_delete_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='name',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polling.register'),
        ),
    ]
