# Generated by Django 4.1.5 on 2023-01-19 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0010_alter_vote_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='like',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='name',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.CharField(default=True, max_length=1000)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polling.register')),
                ('op1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polling.vote')),
            ],
        ),
    ]
