# Generated by Django 4.1.5 on 2023-01-19 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0011_remove_vote_like_remove_vote_name_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polling.questions'),
        ),
    ]
