# Generated by Django 4.1.5 on 2023-01-19 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0012_like_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='like',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='vote',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polling.register'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
