# Generated by Django 4.1.5 on 2023-01-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0013_vote_like_vote_name_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
