# Generated by Django 4.1.5 on 2023-01-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0014_alter_vote_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='op1',
            field=models.CharField(max_length=1000),
        ),
    ]
